<?php

/*
 * This file is part of the swBlogPlugin package.
 *
 * (c) 2010 Thomas Rabaix <thomas.rabaix@soleoweb.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */


/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginswBlogTag extends BaseswBlogTag
{

}