<?php
/*
 * This file is part of the swBlogPlugin package.
 *
 * (c) 2010 Thomas Rabaix <thomas.rabaix@soleoweb.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginswBlogComment extends BaseswBlogComment
{
  const 
    MODERATED_NONE = -1,
    MODERATED_OK   = 1,
    MODERATED_KO   = 0;
  
  public static function getModeratedList()
  {
    
    return array(
      self::MODERATED_NONE => __('option_moderated_none', null, 'swBlogCommentsAdmin'),
      self::MODERATED_OK => __('option_moderated_ok', null, 'swBlogCommentsAdmin'),
      self::MODERATED_KO => __('option_moderated_ko', null, 'swBlogCommentsAdmin'),
    );
  }

  public function getModerationName()
  {
    $list = self::getModeratedList();

    if(!array_key_exists($this->moderated, $list))
    {
      
      return '-';
    }

    return $list[$this->moderated];
  }
}